# Generated by Django 4.1.7 on 2023-06-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_userages_profile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='age',
            new_name='userage_now',
        ),
    ]
