# Generated by Django 4.1.7 on 2023-06-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_userage_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.TextField(blank=True),
        ),
    ]
