# Generated by Django 4.1.7 on 2023-06-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_age_profile_userage_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userage_now',
        ),
    ]
